### ISSUE TITLE
I need screenshots

### ISSUE THREAD

**Issue by farhanaayshath** [sakkeerhussain/qburst-android-plugin#1]
![plugin-3](https://cloud.githubusercontent.com/assets/7835361/23055730/5e21059a-f50d-11e6-98ad-b3670d1e7c03.png)
![plugin-2](https://cloud.githubusercontent.com/assets/7835361/23055729/5e209dee-f50d-11e6-933e-bcde2953d00a.png)
![plugin-1](https://cloud.githubusercontent.com/assets/7835361/23055731/5e215176-f50d-11e6-824a-a8d2a1d469f7.png)

**Comment by sakkeerhussain** [comment]
[QBurstAndroidPlugin_16_02_2017.jar.zip](https://github.com/sakkeerhussain/qburst-android-plugin/files/782512/QBurstAndroidPlugin_16_02_2017.jar.zip)

**Comment by sakkeerhussain** [comment]
![screenshot 2017-02-17 13 35 59](https://cloud.githubusercontent.com/assets/7835361/23057466/5433a7dc-f516-11e6-9788-cdd37273c1c6.png)

**Comment by sakkeerhussain** [comment]
[QBurstAndroidPlugin_17-02-2017.jar.zip](https://github.com/sakkeerhussain/qburst-android-plugin/files/782770/QBurstAndroidPlugin_17-02-2017.jar.zip)

**Comment by sakkeerhussain** [comment]
![screen shot 2017-02-17 at 3 09 20 pm](https://cloud.githubusercontent.com/assets/7835361/23060290/26f98fae-f523-11e6-9d9c-6be6f8012900.png)
